# Generated by Django 4.1.2 on 2023-06-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucketapp', '0002_alter_task_assignee_alter_task_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='description',
        ),
    ]
