# Generated by Django 4.1.2 on 2023-06-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketapp', '0003_rename_content_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
