# Generated by Django 4.2.2 on 2023-06-17 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bucketapp', '0004_task_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='bucketapp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='bucketapp.bucket'),
        ),
    ]
