# Generated by Django 4.2.2 on 2023-06-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucketapp', '0005_alter_task_bucket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='bucketapp',
            new_name='bucket',
        ),
    ]
